package com.openterface.keymod.agent.core;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Execution plan generated by the Agent.
 *
 * <p>Contains a one-line summary and an ordered list of steps.
 * Each step can be terminal (SSH command), hid (wireless keyboard),
 * or macro type.</p>
 */
public final class AgentPlan {

    @NonNull
    public final String summary;

    @NonNull
    public final List<Step> steps;

    public AgentPlan(@NonNull String summary, @NonNull List<Step> steps) {
        this.summary = summary;
        this.steps = Collections.unmodifiableList(new ArrayList<>(steps));
    }

    /** Whether the plan has no steps */
    public boolean isEmpty() {
        return steps.isEmpty();
    }

    /** Total number of steps */
    public int size() {
        return steps.size();
    }

    /**
     * Return a new plan with at most {@code maxSteps} steps.
     * If this plan already has fewer steps, returns this plan unchanged.
     *
     * @param maxSteps maximum number of steps to keep
     * @return truncated plan (re-indexed from 0)
     */
    @NonNull
    public AgentPlan truncateTo(int maxSteps) {
        if (maxSteps < 0) {
            throw new IllegalArgumentException("maxSteps must be >= 0, was " + maxSteps);
        }
        if (steps.size() <= maxSteps) {
            return this;
        }
        List<Step> truncated = steps.subList(0, maxSteps);
        // Re-index steps
        List<Step> reindexed = new ArrayList<>(maxSteps);
        for (int i = 0; i < truncated.size(); i++) {
            Step old = truncated.get(i);
            reindexed.add(new Step(i, old.title, old.command, old.keys, old.macroId, old.kind));
        }
        return new AgentPlan(summary, reindexed);
    }

    /**
     * Return a new plan whose step list is this plan's steps followed by {@code extra}.
     * Steps are re-indexed starting from 0. Used by {@code PlanExecutionUseCase} when
     * continuing with pending steps after an LLM-level retry.
     *
     * @param extra additional steps to append (must not be null)
     * @return new plan with combined steps
     */
    @NonNull
    public AgentPlan withStepsAppended(@NonNull List<Step> extra) {
        if (extra.isEmpty()) {
            return this;
        }
        List<Step> combined = new ArrayList<>(steps.size() + extra.size());
        combined.addAll(steps);
        combined.addAll(extra);
        // Re-index
        List<Step> reindexed = new ArrayList<>(combined.size());
        for (int i = 0; i < combined.size(); i++) {
            Step old = combined.get(i);
            reindexed.add(new Step(i, old.title, old.command, old.keys, old.macroId, old.kind));
        }
        return new AgentPlan(summary, reindexed);
    }

    // ── Step ─────────────────────────────────────────────────────────────

    /**
     * A single execution step.
     *
     * <p>Depending on {@code kind}, different payload fields are populated:
     * <ul>
     *   <li>{@code terminal}: {@link #command} is populated</li>
     *   <li>{@code hid}: {@link #keys} is populated</li>
     *   <li>{@code macro}: {@link #macroId} is populated</li>
     * </ul>
     */
    public static final class Step {

        public final int index;

        @NonNull
        public final String title;

        /** Bash command for terminal mode */
        @Nullable
        public final String command;

        /** Key sequence for HID mode, e.g. {@code "<CMD>s</CMD>"} */
        @Nullable
        public final String keys;

        /** Macro ID or name for macro mode */
        @Nullable
        public final String macroId;

        /** Step kind: {@code "terminal"} | {@code "hid"} | {@code "macro"} */
        @NonNull
        public final String kind;

        public Step(int index,
                    @NonNull String title,
                    @Nullable String command,
                    @Nullable String keys,
                    @Nullable String macroId,
                    @NonNull String kind) {
            this.index = index;
            this.title = title;
            this.command = command;
            this.keys = keys;
            this.macroId = macroId;
            this.kind = kind;
        }

        /** Factory: Terminal step */
        @NonNull
        public static Step terminal(int index, @NonNull String title, @NonNull String command) {
            return new Step(index, title, command, null, null, "terminal");
        }

        /** Factory: HID step */
        @NonNull
        public static Step hid(int index, @NonNull String title, @NonNull String keys) {
            return new Step(index, title, null, keys, null, "hid");
        }

        /** Factory: Macro step */
        @NonNull
        public static Step macro(int index, @NonNull String title, @NonNull String macroId) {
            return new Step(index, title, null, null, macroId, "macro");
        }

        @Override
        @NonNull
        public String toString() {
            return "Step{" + index + ", " + kind + ", \"" + title + "\"}";
        }
    }

    @Override
    @NonNull
    public String toString() {
        return "AgentPlan{summary=\"" + summary + "\", steps=" + steps.size() + "}";
    }
}
